// <auto-generated />
namespace DevStore.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _220520173 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_220520173));
        
        string IMigrationMetadata.Id
        {
            get { return "201705221756318_22052017-3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
